name: .NET Build & UnitTests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 🧪 CI
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          filter: tree:0
          ref: ${{ github.head_ref }}
      - name: ✨ Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: 🛠️ Build
        run: dotnet build "src\IpAddressMonitor.slnx" --configuration Release
      - name: 🧪 Test
        run: dotnet test "src\IpAddressMonitor.slnx" --configuration Release --no-build --verbosity normal
